config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# Handle multi-submit form
class CommitParamConstraint
  def initialize(*param_values)
    @param_values = param_values
  end

  def matches?(request)
    @param_values.any? { |prm| request.params[:commit] == prm.to_s }
  end
end

Rails.application.routes.draw do
  # Dynamic error pages
  get "/404", to: "application#resource_not_found", via: :all
  get "/500", to: "application#internal_error", via: :all

  get "/accessibilite", to: redirect("/pages/declaration-d-accessibilite")
  get "/mentions-legales", to: redirect("/pages/mentions-legales")
  get "/cgu", to: redirect("/pages/conditions-generales-d-utilisation")
  get "/politique-confidentialite", to: redirect("/pages/politique-de-confidentialite")
  get "/suivi", to: redirect("/pages/suivi-d-audience-et-vie-privee")

  # Domains check
  get "/.well-known/pki-validation/:file_name" => "domain_validations#show", :as => :domain_validations

  as :administrator do
    patch "/admin/confirmation" => "administrators/confirmations#update", :as => :update_administrator_confirmation
  end
  devise_for :administrators, path: "admin", controllers: {
    confirmations: "administrators/confirmations",
    sessions: "administrators/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "/users/sign_up/success" => "users/registrations#success", :as => :success_user_registration
  end

  namespace :admin do
    authenticate :administrator do
      mount Sidekiq::Web => "/sidekiq"
      mount MaintenanceTasks::Engine => "/maintenance_tasks"
    end
    resources :cities, only: [:index, :show]
    resources :administrator_emails, only: :index
    resource :account do
      member do
        get :photo
      end
    end
    resources :salary_ranges, only: %i[index]
    resources :email_templates, only: %i[index] do
      collection do
        get :pick
      end
    end
    resources :job_offer_terms, only: %i[index]
    resources :job_offers, path: "offresdemploi" do
      collection do
        post :exports, :feature
        post :init, to: "job_offers#new"
        get :init, to: "job_offer_terms#index"
        get :add_actor, :featured, :archived
        JobOffer.aasm.events.map(&:name).each do |event_name|
          action_name = :"create_and_#{event_name}"
          post :create, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
      end
      member do
        get :export, :board, :stats, :new_transfer, :new_send
        post :transfer, :feature, :unfeature, :send_to_list
        JobOffer.aasm.events.map(&:name).each do |event_name|
          patch(event_name.to_sym)
          action_name = :"update_and_#{event_name}"
          patch :update, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
        namespace :job_offers do
          resources :readings, only: :create
        end
      end
      resources :job_applications, path: "candidatures" do
        member do
          get :cvlm
          get :files
          get :emails
        end
        resource :favorite, only: %i[create destroy]
        resource :unfavorite, only: %i[create destroy]
      end
      resources :archives, only: [:new, :create]
      resources :multiple_recipients_emails, only: %i[new create]
      resources :recipients, only: %i[index create]
    end
    resources :preferred_users, only: :destroy
    resources :preferred_users_lists, path: "liste-candidats" do
      member do
        get :export
        post :send_job_offer
      end
      resources :preferred_users
    end
    resources :users, path: "candidats", except: %i[create] do
      resource :resume, only: %i[show]
      collection do
        post :multi_select
      end
      member do
        get :listing, :photo
        put :update_listing
        post :suspend, :unsuspend, :send_job_offer
      end
    end
    resources :job_applications, path: "candidatures", only: %i[index show update] do
      member do
        patch :change_state
      end
      resources :job_application_files do
        member do
          post :check
          post :uncheck
        end
      end
      resources :rejections, only: %i[create]
      resource :dar, only: %i[update]
      resources :messages, only: %i[create]
      resources :emails, only: %i[create] do
        member do
          post :mark_as_read, :mark_as_unread
          get :attachment
        end
      end
    end
    resources :zip_files, only: :show
    namespace :stats do
      root to: "job_applications#index"
      get :job_offers, to: "job_offers#index"
      resources :job_applications, path: "candidatures", only: %i[index]
    end
    namespace :settings, path: "parametres" do
      resource :positions, only: :update
      resource :organization do
        member do
          get :edit_security
          patch :update_general, :update_display, :update_security
        end
      end
      resources :organization_defaults
      resources :frequently_asked_questions do
        member do
          post :move_higher, :move_lower
        end
      end

      resources :pages do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :cmgs do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :administrators, path: "administrateurs" do
        collection do
          get :export
          get :inactive
        end
        member do
          post :resend_confirmation_instructions
          post :send_unlock_instructions
          post :deactivate
          post :reactivate
          post :transfer
        end
      end
      resources :employers, :categories do
        member do
          post :move_left, :move_right
        end
      end
      resources :salary_ranges
      resources :job_application_file_types
      other_settings = %i[
        availability_ranges
        archiving_reasons benefit drawbacks bops email_template job_application_file_types rejection_reasons
        contract_duration foreign_languages foreign_language_levels job_offer_terms user_menu_links
      ]
      (JobOffer::SETTINGS + other_settings).each do |setting|
        resources setting.to_s.pluralize.to_sym, except: %i[show] do
          member do
            post :move_higher, :move_lower
          end
        end
      end
      root to: "administrators#index"
    end
    root to: "job_offers#index"
  end

  authenticate :user do
    namespace "account", path: "espace-candidat" do
      resource :profiles, path: "mon-profil", only: [] do
        resource :resume, only: :show
        collection do
          get :edit
          patch :update
        end
      end
      resources :job_applications, path: "mes-candidatures" do
        member do
          get :job_offer, path: "offre"
        end
        resources :job_application_files, path: "documents"
        resources :emails, only: %i[index create] do
          member do
            get :attachment
          end
        end
      end
      resource :user, path: "mon-compte", only: %i[show destroy] do
        collection do
          get :edit
          patch :update
        end
        member do
          get :change_email, :change_password, :photo
          patch :update_email, :update_password, :unlink_france_connect, :set_password
        end
      end
    end
  end

  resources :job_offers, path: "offresdemploi", only: %i[index show] do
    collection do
      get :apply
    end
    member do
      get :apply, to: "job_offers#old_apply"
      post :send_application
      get :successful
      resources :bookmarks, only: %i[create destroy], path: "favoris"
    end
  end

  resources :downloads, only: %i[show]
  resources :pages, only: %w[show]
  resource :robots, only: %w[show]
  resource :sitemap
  resource :maintenance, only: %w[show]

  root to: "homepages#show"
end

app/controllers/homepages_controller.rb
# frozen_string_literal: true

class HomepagesController < ApplicationController
  # GET /
  def show
    @page = current_organization.pages.where(parent_id: nil).first
    root_rel = current_organization.job_offers
      .publicly_visible
      .includes(:contract_type)
      .order(published_at: :asc)
    @job_offers_selected = root_rel.where(featured: true)
    @job_offers_last = root_rel.limit(6)

    @categories = Category.order("lft ASC").where(
      "published_job_offers_count > ? AND depth <= ?", 0, 1
    )

    @contract_types = ContractType.all
  end
end

app/views/homepages/_faq.html.haml
- if FrequentlyAskedQuestion.count > 0
  .rf-container.rf-my-9w
    .rf-grid-row.rf-grid-row--center
      .rf-col-12
        %h2.rf-h3.text-center.rf-mt-0.rf-mb-4w Foire aux questions
      .rf-col-12
        .rf-accordions-group
          - FrequentlyAskedQuestion.all.each_with_index do |faq, index|
            %section.rf-accordion
              %h3.rf-accordion__title
                %button.rf-accordion__btn{"aria-controls" => "accordion-#{index}", "aria-expanded" => "false"}
                  = faq.name
              %div.rf-collapse{id: "accordion-#{index}"}
                = sanitize(faq.value)

app/views/homepages/_hero.html.haml
.fr-container
  .fr-grid-row.fr-grid-row--gutters.fr-grid-row--center.fr-mb-0
    .fr-col-12.fr-col-md-11.fr-col-lg-10
      .fr-grid-row.fr-hero
        - illustration_url = current_organization.image_background.url if current_organization.image_background.present?
        .fr-col-12.d-flex.flex-column.align-items-center.justify-content-center{class: illustration_url.present? ? 'fr-col-md-6' : nil}
          %h1.text-justify.fr-h2.fr-mb-0= @page_title
        - if illustration_url.present?
          .fr-col-12.fr-col-md-6.fr-pl-9w.d-flex.flex-column.align-items-center.justify-content-center
            = image_tag illustration_url, style: 'max-width:100%;'

app/views/homepages/_job_offer_headline_card.html.haml
.rf-col-12.rf-col-md-6.rf-col-lg-4
  .rf-card.rounded-lg
    = link_to job_offer do
      .rf-card__body
        %h4.rf-card__title
          = job_offer.title
        %p.rf-card__desc
          = job_offer_contract_type_display(job_offer)
          %br
          = job_offer.location
        - if job_offer.published_at.present?
          .rf-card__detail
            = t('job_offers.job_offer.published_date', time_ago_in_words: time_ago_in_words(job_offer.published_at))

app/views/homepages/_job_offer_headlines.html.haml
- if @job_offers_selected.count > 0
  .fr-container.fr-my-9w
    .fr-grid-row
      %h2.fr-h3.fr-mb-2w Nos offres à la une
    .fr-grid-row.fr-grid-row--gutters.fr-card-deck.fr-mb-0
      = render partial: 'job_offer_headline_card', collection: @job_offers_selected, as: :job_offer

app/views/homepages/_job_offer_last.html.haml
%section.fr-py-9w.fr-bg-beige
  .fr-container
    .fr-grid-row.fr-grid-row--gutters
      .fr-col-12
        %h2.fr-h3.fr-mb-4w Nos dernières offres
    .fr-grid-row.fr-grid-row--gutters.job-offer-grid
      = render collection: @job_offers_last, partial: 'job_offers/job_offer', locals: { container_class: %w[fr-col-12 fr-col-md-6] }
    .fr-grid-row.fr-grid-row--center.fr-mt-4w
      = link_to "Voir toutes nos offres", :job_offers, class: "fr-btn"

app/views/homepages/_job_offer_search_form.html.haml
= form_tag job_offers_url, method: :get, class: 'w-100 form-inline' do
  .rf-input-group
    = text_field_tag :q, params[:q], placeholder: 'Mot-clé', class: 'rf-input'
  - cache [@categories, params[:category_id]] do
    .rf-input-group
      - options = options_from_collection_for_select(@categories, "id", "name_with_depth", params[:category_id])
      - prompt = t('job_offers.filter.select_category')
      = select_tag "category_id", options, include_blank: false, prompt: prompt, data: {placeholder: prompt, 'allow-clear': true}, class: 'rf-select'
  - cache [@contract_types, params[:contract_type_id]] do
    .rf-input-group
      - prompt = t('job_offers.filter.select_contract_type')
      = select_tag "contract_type_id", options_from_collection_for_select(@contract_types, "id", "name", params[:contract_type_id]), include_blank: false, prompt: prompt, data: {placeholder: prompt, 'allow-clear': true}, class: 'rf-select'
  = submit_tag t('job_offers.filters.search'), name: nil, class: 'rf-btn'

app/views/homepages/_search.html.haml
.fr-container.fr-mb-9w.fr-mt-4w
  .fr-grid-row.fr-grid-row--gutters
    .fr-col-12
      = form_tag job_offers_url, method: :get, class: 'fr-search-bar fr-search-bar--lg' do
        %label.fr-label{for: "q"}
          Mots-clés recherchés parmi les offres d'emploi
        = search_field_tag :q, params[:q], placeholder: 'Recherche par mot-clé dans les offres d\'emploi', class: 'fr-input'
        %button.fr-btn.fr-btn--lg{:title => "Rechercher"}
          Rechercher
    .fr-col-12.text-center
      = link_to "Recherche avancée", job_offers_path, class: 'fr-link fr-fi-arrow-right-line fr-link--icon-right'

app/views/homepages/_testimony.html.haml
- if current_organization.testimony_title.present?
  - style = current_organization.testimony_logo.present? ? "background-image: linear-gradient(var(--bg-image), var(--bg-image)), url(#{ current_organization.testimony_logo.url });" : nil
  %section.fr-bg--alt-2.fr-bg--hero-image.d-flex.align-items-center.fr-py-9w{style: style}
    .fr-container
      .fr-grid-row.fr-grid-row--center
        .fr-h2.font-weight-bold.text-uppercase.fr-mb-0
          = current_organization.testimony_title
      .fr-grid-row.fr-grid-row--center
        .fr-text--lead.text-uppercase.fr-mb-3w
          = current_organization.testimony_subtitle
      .fr-grid-row.fr-grid-row--center
        = link_to 'Voir plus', current_organization.testimony_url, class: 'fr-btn', target: "_blank"

app/views/homepages/show.html.haml
- @page_title = @page&.title || t('.title')
= render partial: 'hero'
= render partial: 'search'
= render partial: 'job_offer_headlines'
= render partial: 'job_offer_last'
= render partial: 'testimony'
= render partial: 'faq'