config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# Handle multi-submit form
class CommitParamConstraint
  def initialize(*param_values)
    @param_values = param_values
  end

  def matches?(request)
    @param_values.any? { |prm| request.params[:commit] == prm.to_s }
  end
end

Rails.application.routes.draw do
  # Dynamic error pages
  get "/404", to: "application#resource_not_found", via: :all
  get "/500", to: "application#internal_error", via: :all

  get "/accessibilite", to: redirect("/pages/declaration-d-accessibilite")
  get "/mentions-legales", to: redirect("/pages/mentions-legales")
  get "/cgu", to: redirect("/pages/conditions-generales-d-utilisation")
  get "/politique-confidentialite", to: redirect("/pages/politique-de-confidentialite")
  get "/suivi", to: redirect("/pages/suivi-d-audience-et-vie-privee")

  # Domains check
  get "/.well-known/pki-validation/:file_name" => "domain_validations#show", :as => :domain_validations

  as :administrator do
    patch "/admin/confirmation" => "administrators/confirmations#update", :as => :update_administrator_confirmation
  end
  devise_for :administrators, path: "admin", controllers: {
    confirmations: "administrators/confirmations",
    sessions: "administrators/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "/users/sign_up/success" => "users/registrations#success", :as => :success_user_registration
  end

  namespace :admin do
    authenticate :administrator do
      mount Sidekiq::Web => "/sidekiq"
      mount MaintenanceTasks::Engine => "/maintenance_tasks"
    end
    resources :cities, only: [:index, :show]
    resources :administrator_emails, only: :index
    resource :account do
      member do
        get :photo
      end
    end
    resources :salary_ranges, only: %i[index]
    resources :email_templates, only: %i[index] do
      collection do
        get :pick
      end
    end
    resources :job_offer_terms, only: %i[index]
    resources :job_offers, path: "offresdemploi" do
      collection do
        post :exports, :feature
        post :init, to: "job_offers#new"
        get :init, to: "job_offer_terms#index"
        get :add_actor, :featured, :archived
        JobOffer.aasm.events.map(&:name).each do |event_name|
          action_name = :"create_and_#{event_name}"
          post :create, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
      end
      member do
        get :export, :board, :stats, :new_transfer, :new_send
        post :transfer, :feature, :unfeature, :send_to_list
        JobOffer.aasm.events.map(&:name).each do |event_name|
          patch(event_name.to_sym)
          action_name = :"update_and_#{event_name}"
          patch :update, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
        namespace :job_offers do
          resources :readings, only: :create
        end
      end
      resources :job_applications, path: "candidatures" do
        member do
          get :cvlm
          get :files
          get :emails
        end
        resource :favorite, only: %i[create destroy]
        resource :unfavorite, only: %i[create destroy]
      end
      resources :archives, only: [:new, :create]
      resources :multiple_recipients_emails, only: %i[new create]
      resources :recipients, only: %i[index create]
    end
    resources :preferred_users, only: :destroy
    resources :preferred_users_lists, path: "liste-candidats" do
      member do
        get :export
        post :send_job_offer
      end
      resources :preferred_users
    end
    resources :users, path: "candidats", except: %i[create] do
      resource :resume, only: %i[show]
      collection do
        post :multi_select
      end
      member do
        get :listing, :photo
        put :update_listing
        post :suspend, :unsuspend, :send_job_offer
      end
    end
    resources :job_applications, path: "candidatures", only: %i[index show update] do
      member do
        patch :change_state
      end
      resources :job_application_files do
        member do
          post :check
          post :uncheck
        end
      end
      resources :rejections, only: %i[create]
      resource :dar, only: %i[update]
      resources :messages, only: %i[create]
      resources :emails, only: %i[create] do
        member do
          post :mark_as_read, :mark_as_unread
          get :attachment
        end
      end
    end
    resources :zip_files, only: :show
    namespace :stats do
      root to: "job_applications#index"
      get :job_offers, to: "job_offers#index"
      resources :job_applications, path: "candidatures", only: %i[index]
    end
    namespace :settings, path: "parametres" do
      resource :positions, only: :update
      resource :organization do
        member do
          get :edit_security
          patch :update_general, :update_display, :update_security
        end
      end
      resources :organization_defaults
      resources :frequently_asked_questions do
        member do
          post :move_higher, :move_lower
        end
      end

      resources :pages do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :cmgs do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :administrators, path: "administrateurs" do
        collection do
          get :export
          get :inactive
        end
        member do
          post :resend_confirmation_instructions
          post :send_unlock_instructions
          post :deactivate
          post :reactivate
          post :transfer
        end
      end
      resources :employers, :categories do
        member do
          post :move_left, :move_right
        end
      end
      resources :salary_ranges
      resources :job_application_file_types
      other_settings = %i[
        availability_ranges
        archiving_reasons benefit drawbacks bops email_template job_application_file_types rejection_reasons
        contract_duration foreign_languages foreign_language_levels job_offer_terms user_menu_links
      ]
      (JobOffer::SETTINGS + other_settings).each do |setting|
        resources setting.to_s.pluralize.to_sym, except: %i[show] do
          member do
            post :move_higher, :move_lower
          end
        end
      end
      root to: "administrators#index"
    end
    root to: "job_offers#index"
  end

  authenticate :user do
    namespace "account", path: "espace-candidat" do
      resource :profiles, path: "mon-profil", only: [] do
        resource :resume, only: :show
        collection do
          get :edit
          patch :update
        end
      end
      resources :job_applications, path: "mes-candidatures" do
        member do
          get :job_offer, path: "offre"
        end
        resources :job_application_files, path: "documents"
        resources :emails, only: %i[index create] do
          member do
            get :attachment
          end
        end
      end
      resource :user, path: "mon-compte", only: %i[show destroy] do
        collection do
          get :edit
          patch :update
        end
        member do
          get :change_email, :change_password, :photo
          patch :update_email, :update_password, :unlink_france_connect, :set_password
        end
      end
    end
  end

  resources :job_offers, path: "offresdemploi", only: %i[index show] do
    collection do
      get :apply
    end
    member do
      get :apply, to: "job_offers#old_apply"
      post :send_application
      get :successful
      resources :bookmarks, only: %i[create destroy], path: "favoris"
    end
  end

  resources :downloads, only: %i[show]
  resources :pages, only: %w[show]
  resource :robots, only: %w[show]
  resource :sitemap
  resource :maintenance, only: %w[show]

  root to: "homepages#show"
end

app/models/job_application/notifiable.rb
module JobApplication::Notifiable
  extend ActiveSupport::Concern
  included do
    after_update :notify_applicant_new_state, if: -> { new_state_requires_applicant_notification? }
    after_update :notify_hr_managers_contract_drafting, if: -> { saved_change_to_state? && contract_drafting? }
    after_update :notify_hr_managers_contract_feedback_waiting, if: -> { saved_change_to_state? && contract_feedback_waiting? }
    after_update :notify_payroll_managers_contract_received, if: -> { saved_change_to_state? && contract_received? }
    after_update :notify_managers_affected, if: -> { saved_change_to_state? && affected? }
  end

  private

  def notify_applicant_new_state
    ApplicantNotificationsMailer.with(user:, job_offer:, state:).notify_new_state.deliver_later
  end

  def new_state_requires_applicant_notification?
    saved_change_to_state? && JobApplication::NOTIFICATION_STATES.include?(state.to_s)
  end

  def notify_hr_managers_contract_drafting
    job_offer_hr_managers.each do |administrator|
      notify_admin_new_state(administrator, :contract_drafting)
    end
  end

  def notify_hr_managers_contract_feedback_waiting
    job_offer_hr_managers.each do |administrator|
      notify_admin_new_state(administrator, :contract_feedback_waiting)
    end
  end

  def notify_payroll_managers_contract_received
    job_offer_payroll_managers.each do |administrator|
      notify_admin_new_state(administrator, :contract_received)
    end
  end

  def notify_managers_affected
    (job_offer_hr_managers + job_offer_payroll_managers).each do |administrator|
      notify_admin_new_state(administrator, :affected)
    end
  end

  def notify_admin_new_state(administrator, state)
    NotificationsMailer.with(administrator:, job_application: self).send(state).deliver_later
  end
end

app/models/job_application/readable.rb
# frozen_string_literal: true

module JobApplication::Readable
  extend ActiveSupport::Concern

  def mark_all_as_read!
    emails.map(&:mark_as_read!)
    job_application_files.map(&:check!)
    compute_notifications_counter!
  end
end

app/controllers/account/job_applications_controller.rb
# frozen_string_literal: true

class Account::JobApplicationsController < Account::BaseController
  before_action :set_job_application, except: %i[index]

  # GET /account/job_applications
  # GET /account/job_applications.json
  def index
    @job_applications_ongoing = job_applications.not_rejecteds
    @job_applications_finished = job_applications.rejecteds
  end

  def job_offer
    render layout: "account/job_application_display"
  end

  # GET /account/job_applications/1
  # GET /account/job_applications/1.json
  def show
    @emails = @job_application.emails.order(created_at: :desc)
    @email = @job_application.emails.new

    render layout: "account/job_application_display"
  end

  private

  def job_applications
    current_user.job_applications.includes(job_offer: [:contract_type]).order(created_at: :desc)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_job_application
    id = params[:job_application_id] || params[:id]
    @job_application = current_user.job_applications.find(id)
    @job_offer = @job_application.job_offer
  end
end

app/controllers/admin/job_applications_controller.rb
# frozen_string_literal: true

class Admin::JobApplicationsController < Admin::BaseController
  # GET /admin/candidatures
  # GET /admin/candidatures.json
  def index
    @contract_types = ContractType.all
    @employers = Employer.tree
    @preferred_users_lists = current_administrator.preferred_users_lists

    @job_applications = @job_applications.includes(:job_offer, :user)
    @q = @job_applications.ransack(params[:q])
    @job_applications_filtered = @q.result.yield_self { |relation|
      if params[:s].present?
        relation.search_full_text(params[:s])
      else
        relation
      end
    }.yield_self { |relation|
      relation.paginate(page: params[:page], per_page: 25)
    }
    build_employer_ids

    render action: :index, layout: "admin/pool"
  end

  # GET /admin/candidatures/1
  # GET /admin/candidatures/1.json
  def show
    user = @job_application.user
    if user.blank?
      redirect_to admin_job_offer_path(@job_application.job_offer), notice: t(".user_deleted")
    else
      @other_job_applications = user && user.job_applications.where.not(id: @job_application.id)
      render action: :show, layout: layout_choice
    end
  end

  alias_method :cvlm, :show
  alias_method :emails, :show
  alias_method :files, :show

  # PATCH/PUT /admin/candidatures/1
  # PATCH/PUT /admin/candidatures/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to [:admin, @job_application], notice: t(".success") }
        format.js do
          @notification = t(".success")
          render :update
        end
      else
        format.html { render :edit }
        format.js do
          @notification = t(".failure")
          render :update, status: :unprocessable_entity
        end
      end
    end
  end

  def change_state
    @state = params[:state] || params.dig(:job_application, :state)
    known_aasm_state = @job_application.aasm.states.detect { |s| s.name.to_s == @state }
    raise ForbiddenState.new(state: @state) if known_aasm_state.nil?

    @job_application.send(:"#{known_aasm_state.name}!")
    @job_offer = @job_application.job_offer
    state_i18n = JobApplication.human_attribute_name("state/#{@state}")

    current_max = @job_offer.current_most_advanced_job_applications_state
    if @job_offer.most_advanced_job_applications_state_before_type_cast != current_max
      @job_offer.update(most_advanced_job_applications_state: current_max)
    end

    @notification = t(".success", state: state_i18n)
    render_reponse
  rescue ActiveRecord::RecordInvalid
    @notification = @job_application.errors.messages[:state].join(" ")
    render_reponse
  end

  def render_reponse
    respond_to do |format|
      format.html do
        redirect_back(fallback_location: [:admin, @job_application], notice: @notification)
      end
      format.js do
        render :change_state
      end
      format.json { render :show, status: :ok, location: @job_application }
    end
  end

  private

  def set_job_application = @job_application = JobApplication.find(params[:id])

  def job_application_params
    params.require(:job_application).permit(:skills_fit_job_offer, :experiences_fit_job_offer, :rejection_reason_id)
  end

  def layout_choice
    if params[:job_offer_id].present?
      @job_offer = JobOffer.find(params[:job_offer_id])
      @layout_full_width = true
      request.xhr? ? false : "admin/job_offer_single"
    else
      request.xhr? ? false : "admin/pool"
    end
  end

  def build_employer_ids
    @employer_ids = @job_applications_filtered.map(&:employer_id).uniq
  end
end

app/helpers/admin/job_applications_helper.rb
# frozen_string_literal: true

module Admin::JobApplicationsHelper
  def job_application_modal_section_classes(additional_class = nil)
    case additional_class
    when "pb-0"
      %w[px-4 pt-4].push(additional_class)
    else
      %w[px-4 py-4]
    end
  end

  def job_applications_tab_active
    @job_applications_tab_active ||= if controller.controller_name == "job_applications"
      case controller.action_name
      when "show"
        :profile
      when "cvlm"
        :cvlm
      when "emails"
        :emails
      when "files"
        :files
      end
    end
  end

  def in_place_edit_value_formatted(content, field)
    case field
    when :availability_date_in_month
      "#{content} mois"
    when :gender, :is_currently_employed
      Profile.human_attribute_name("#{field}/#{content}")
    else
      content
    end
  end

  def in_place_edit_value(obj, opts = {})
    res = nil

    if (m = opts.delete(:field))
      res = obj.send(m)
    elsif (association = opts.delete(:association))
      res = obj.send(association)&.name
    end

    return content_tag("em", "Non défini(e)") if res.to_s.blank?

    in_place_edit_value_formatted(res, m)
  end

  def choices_boolean
    [
      [Profile.human_attribute_name("is_currently_employed/true"), true],
      [Profile.human_attribute_name("is_currently_employed/false"), false]
    ]
  end

  def choices_gender
    Profile.genders.each_with_object([]) do |(k, _), ary|
      str = Profile.human_attribute_name("gender/#{k}")
      ary << [str, k]
    end
  end

  def job_application_resume_url(job_application)
    return unless job_application

    target_state = JobApplication.states["initial"]
    target_file_type = JobApplicationFileType.where(from_state: target_state, kind: :applicant_provided)
    job_application_files = job_application.job_application_files.where(job_application_file_type: target_file_type).joins(:job_application_file_type).order("job_application_file_types.position")
    job_application_file = job_application_files.limit(1).first
    if job_application_file&.document_content&.present?
      url_for([:admin, job_application, job_application_file, {format: :pdf}])
    end
  end
end

app/helpers/job_applications_helper.rb
# frozen_string_literal: true

module JobApplicationsHelper
  def badge_color_for_state(state)
    case state.to_sym
    when :start
      "light invisible"
    when :initial
      "purple"
    when :draft, :archived, :suspended
      "light-gray"
    when :accepted, :published
      "success"
    when :contract_drafting, :contract_feedback_waiting, :contract_received, :affected
      "primary"
    when :phone_meeting, :to_be_met
      "info"
    end
  end

  def badge_class(state)
    "badge-#{badge_color_for_state(state)}"
  end
end

app/views/admin/job_applications/_filter_employer.html.haml
- search_key = :job_offer_employer_id_in
- ary = params.dig(:q, search_key)  || []
.dropdown.dropdown-checks.form-group
  %button.form-control.dropdown-toggle.text-left.d-flex.align-items-center#dropdownEmployeur{type: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false}}
    Employeur
    - if ary.any?
      = "(#{ary.size})"
  .dropdown-menu.dropdown-menu-right.allow-focus{aria: {labelledby: 'dropdownEmployeur'}}
    - grouped_options = Employer.roots.map{|x| [x.name, x.children]}
    %ul
      - for option in grouped_options
        %li
          = option.first
          %ul
            - for sub_option in option.last
              - if current_administrator.admin? || @employer_ids.include?(sub_option.id)
                - input_id = dom_id(sub_option)
                %li
                  .form-check.form-check-inline.w-100
                    - checked = ary.include?(sub_option.id)
                    = check_box_tag "q[#{search_key}][]", sub_option.id, checked, class: 'form-check-input', id: input_id
                    %label.form-check-label.text-truncate.d-block{for: input_id}= sub_option.name

app/views/admin/job_applications/_filter_state.html.haml
- search_key = :state_in
- ary = params.dig(:q, search_key)  || []
- states = JobApplication.states.to_a.map {|k| [ JobApplication.human_attribute_name("state/#{k.first}"), k.last] }
.dropdown.dropdown-checks.form-group
  %button.form-control.dropdown-toggle.text-left.d-flex.align-items-center#dropdownContractType{type: 'button', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false}}
    État
    - if ary.any?
      = "(#{ary.size})"
  .dropdown-menu.dropdown-menu-right.allow-focus{aria: {labelledby: 'dropdownContractType'}}
    %ul
      - for state_ary in states
        - state_name = state_ary[0]
        - state_id = state_ary[1]
        - input_id = "state_#{state_id}"
        %li
          .form-check.form-check-inline.w-100
            - checked = ary.include?(state_id.to_s)
            = check_box_tag "q[#{search_key}][]", state_id, checked, class: 'form-check-input', id: input_id
            %label.form-check-label.text-truncate.d-block{for: input_id}= state_name

app/views/admin/job_applications/_form.html.haml
= simple_form_for([:admin, @job_application]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :job_offer
    = f.association :user

  .form-actions
    = f.button :submit

app/views/admin/job_applications/_job_application.html.haml
= render partial: '/admin/users/user', locals: {user: job_application.user, job_application: job_application}

app/views/admin/job_applications/_job_application_dar.html.haml
- if can? :validate_dar, job_application
  = simple_form_for job_application, url: admin_job_application_dar_path(job_application), namespace: "dar_#{job_application.id}", html: { class: 'mx-3', data: { controller: 'auto-submit' } } do |f|
    = f.input :dar, as: :radio_buttons, input_html: { data: { action: 'change->auto-submit#submit' } }
- else
  .mx-3
    %fieldset.form-group.rf-input-group.rf-fieldset.radio_buttons{disabled: true}
      %legend.col-form-label.pt-0= t('simple_form.labels.job_application.dar')
      .form-check.form-check-inline
        = radio_button_tag "dar_#{job_application.id}_readonly", "true", job_application.dar == true, class: "form-check-input", disabled: true
        = label_tag nil, t("true"), class: "form-check-label"
      .form-check.form-check-inline
        = radio_button_tag "dar_#{job_application.id}_readonly", "false", job_application.dar == false, class: "form-check-input", disabled: true
        = label_tag nil, t("false"), class: "form-check-label"

app/views/admin/job_applications/_job_application_files.html.haml
- to_be_provided_files = @job_application.to_be_provided_files
- other_available_file_types = @job_application.other_available_file_types
.card.job-application-files
  .card-header.with-subheader.bg-white.font-weight-bold.text-secondary
    = fa_icon('file-document', class: 'text-secondary')
    = t('.title')
  .card-subheader.bg-card-bg.font-weight-bold.text-muted
    = t('.subtitle_1')
  .card-body.bg-white.files-list
    - if to_be_provided_files.any?
      = render partial: "/admin/job_application_files/job_application_file", locals: {job_application: @job_application}, collection: to_be_provided_files
    - else
      %em= t('.none_atm')
  .card-subheader.bg-card-bg.font-weight-bold.text-muted
    = t('.subtitle_2')
  .card-body.bg-white.files-list
    %small.text-italic.d-block.mb-3= t('.note')
    - if other_available_file_types.any?
      = render partial: "/admin/job_application_files/available_job_application_file_type", locals: {job_application: @job_application}, collection: other_available_file_types, as: :job_application_file_type
    - else
      %em= t('.none')

app/views/admin/job_applications/_job_application_profile.html.haml
- job_offer = job_application.job_offer
.card{id: dom_id(job_application, 'profile')}
  .card-header.bg-white.font-weight-bold.text-secondary
    = fa_icon('file-document', class: 'text-secondary')
    Spécificités vis-à-vis de l'offre sélectionnée
  .card-body.bg-white
    - fields = job_application_profile_fields
    - fields.each do |field|
      - hsh = { job_application: job_application, field: field, disabled: job_offer.archived? }
      = render partial: '/admin/user_profiles/user_profile_field', locals: hsh

app/views/admin/job_applications/_job_application_profile_field_input.html.haml
- in_place_icon = fa_icon('pencil', class: 'icon text-primary')
- in_place_value = in_place_edit_value(f.object, field: field) if local_variables.include?(:field)
- in_place_value = in_place_edit_value(f.object, association: association) if local_variables.include?(:association)
- if local_variables.include?(:choices)
  = f.input field, collection: choices, include_blank: true, wrapper: :horizontal_multi_select, label_html: {class: 'mb-0'}, input_html: {class: 'w-auto d-none'}, in_place_value: in_place_value, in_place_icon: in_place_icon
- elsif local_variables.include?(:field)
  - if field == :nationality
    = f.input field, as: :country, include_blank: true, wrapper: :horizontal_multi_select, label_html: {class: 'mb-0'}, input_html: {class: 'w-100 d-none'}, in_place_value: in_place_value, in_place_icon: in_place_icon
  - elsif field == :birth_date
    = f.input field, start_year: 1900, include_blank: true, wrapper: :horizontal_multi_select, label_html: {class: 'mb-0'}, input_html: {class: 'w-auto d-none'}, in_place_value: in_place_value, in_place_icon: in_place_icon
  - elsif f.object.class.columns.detect{|x| x.name == field.to_s}&.type == :boolean
    = f.input field, as: :radio_buttons, wrapper: :horizontal_collection_inline, label_html: {class: 'mb-0'}
  - else
    - do_not_truncate = true if field == :address
    = f.input field, label_html: {class: 'mb-0'}, input_html: {class: 'w-100 d-none'}, in_place_value: in_place_value, in_place_icon: in_place_icon, do_not_truncate: do_not_truncate
    - if field == :address
      - address_fields.each do |field|
        = f.hidden_field field
- elsif local_variables.include?(:association)
  = f.association association, wrapper: :horizontal_multi_select, label_html: {class: 'mb-0'}, input_html: {class: 'w-100 d-none'}, in_place_value: in_place_value, in_place_icon: in_place_icon

app/views/admin/job_applications/_user_job_applications.html.haml
.card
  .card-header.bg-white.font-weight-bold.text-secondary
    = fa_icon('file-lines', class: 'text-secondary')
    - if defined?(narrow)
      = t('.title_narrow')
    - else
      = t('.title')
  .card-body.bg-white.py-0{class: defined?(narrow) ? 'px-0' : nil}
    %table.table.table-hover.mb-0.mt-0.small
      %thead
        %tr
          %th.border-0.text-center{style: 'width: 23px;'}
            = t('.image')
          - unless defined?(narrow)
            %th.border-0{style: 'width: 140px;'}
              = t('.offer')
          %th.border-0
            = t('.statut')
          %th.border-0.text-right{style: 'width: 10char;'}
            = t('.date')
      %tbody
        - for job_application in job_applications
          - job_offer = job_application.job_offer
          %tr
            %td.border-0.text-center
              = link_to job_offer.identifier, [:admin, job_offer], title: job_offer.title
            - unless defined?(narrow)
              %td.border-0
                .text-truncate{style: 'width: 140px;'}
                  = job_offer.title
            %td.border-0
              = link_to [:admin, job_offer, job_application] do
                - if job_application.rejected
                  = t("activerecord.attributes.job_application.rejected")
                - else
                  = JobApplication.human_attribute_name("state/#{job_application.state}")
            %td.border-0.text-right
              = l job_application.created_at.to_date

app/views/admin/job_applications/change_state.js.erb
Snackbar.show({text: '<%= @notification %>', showAction: false})
var nodeBoard = document.querySelector('#board')
if (nodeBoard !== null) {
  window.boardRedraw()
} else {
  window.reloadWithTurbo()
}

app/views/admin/job_applications/emails.html.haml
- id = dom_id(@job_application, 'emails')
- emails = @job_application.emails.order(created_at: :desc).includes(:sender)
.d-flex.flex-column{id: id}
  = render partial: '/admin/emails/form' if can? :manage, Email
  - if emails.any?
    = render partial: '/admin/emails/email', collection: emails, as: :email
  - else
    %em Aucun courrier échangé.

app/views/admin/job_applications/files.html.haml
- result = @job_application.files_to_be_provided
- must_be_provided_files = result[:must_be_provided_files]
- optional_file_types = result[:optional_file_types]

.card.job-application-files
  .card-header.with-subheader.bg-white.font-weight-bold.text-secondary
    = fa_icon('file-lines', class: 'text-secondary')
    = t('.title')
  .card-subheader.bg-card-bg.font-weight-bold.text-muted
    = t('.subtitle_1')
  .card-body.bg-white.files-list
    - if must_be_provided_files.any?
      = render partial: "/admin/job_application_files/job_application_file", collection: must_be_provided_files
    - else
      %em= t('.none_atm')
  .card-subheader.bg-card-bg.font-weight-bold.text-muted
    = t('.subtitle_2')
  .card-body.bg-white.files-list
    %small.text-italic.d-block.mb-3= t('.note')
    - if optional_file_types.any?
      = render partial: "/admin/job_application_files/optional_job_application_file_type", collection: optional_file_types, as: :job_application_file_type, locals: {job_application: @job_application}
    - else
      %em= t('.none')

app/views/admin/job_applications/index.html.haml
- @page_title = t('.title')
.card
  .card-header
    .h4.text-primary.d-md-flex.align-items-center
      #{@job_applications.count} candidatures
    = render partial: 'search'
    .d-flex.align-items-end
      .h5.text-primary.mr-auto= t('.job_applications_filtered', count: @job_applications_filtered.count)
      - klasses = %w[btn btn-link mb-0]
      = sort_link(@q, :created_at, {}, {class: klasses}) do
        Date de création
        - unless @q.sorts.detect{|x| x.name == 'created_at'}
          &nbsp;▼
    .row
      .col-12
        - if @job_applications_filtered.any?
          .card.bg-transparent
            .card-body
              .row
                .col-12.user-full-name
                  Nom
                .col-12.personal-profile-current-position
                  Métier
                .col-12.personal-profile-is-currently-employed
                  Statut
                .col-12.user-job-applications-count
                  Candidatures
                .col-12.personal-profile-address-short
                  Secteur
          = render partial: 'job_application', collection: @job_applications_filtered
          .mt-5
            = will_paginate @job_applications_filtered, params: { controller: 'job_applications', action: controller.action_name }
        - else
          %em Aucun résultat

.modal.fade#remoteContentModal{tabindex: -1, role: :dialog, aria: {labelledby: :remoteContentModal, hidden: true}}
  .modal-dialog.modal-lg{role: :document}
    .modal-content
      .modal-body.p-0

app/views/admin/job_applications/update.js.erb
Snackbar.show({text: '<%= @notification %>', showAction: false})
formAutoSubmit()
window.reloadWithTurbo()