config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# Handle multi-submit form
class CommitParamConstraint
  def initialize(*param_values)
    @param_values = param_values
  end

  def matches?(request)
    @param_values.any? { |prm| request.params[:commit] == prm.to_s }
  end
end

Rails.application.routes.draw do
  # Dynamic error pages
  get "/404", to: "application#resource_not_found", via: :all
  get "/500", to: "application#internal_error", via: :all

  get "/accessibilite", to: redirect("/pages/declaration-d-accessibilite")
  get "/mentions-legales", to: redirect("/pages/mentions-legales")
  get "/cgu", to: redirect("/pages/conditions-generales-d-utilisation")
  get "/politique-confidentialite", to: redirect("/pages/politique-de-confidentialite")
  get "/suivi", to: redirect("/pages/suivi-d-audience-et-vie-privee")

  # Domains check
  get "/.well-known/pki-validation/:file_name" => "domain_validations#show", :as => :domain_validations

  as :administrator do
    patch "/admin/confirmation" => "administrators/confirmations#update", :as => :update_administrator_confirmation
  end
  devise_for :administrators, path: "admin", controllers: {
    confirmations: "administrators/confirmations",
    sessions: "administrators/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    get "/users/sign_up/success" => "users/registrations#success", :as => :success_user_registration
  end

  namespace :admin do
    authenticate :administrator do
      mount Sidekiq::Web => "/sidekiq"
      mount MaintenanceTasks::Engine => "/maintenance_tasks"
    end
    resources :cities, only: [:index, :show]
    resources :administrator_emails, only: :index
    resource :account do
      member do
        get :photo
      end
    end
    resources :salary_ranges, only: %i[index]
    resources :email_templates, only: %i[index] do
      collection do
        get :pick
      end
    end
    resources :job_offer_terms, only: %i[index]
    resources :job_offers, path: "offresdemploi" do
      collection do
        post :exports, :feature
        post :init, to: "job_offers#new"
        get :init, to: "job_offer_terms#index"
        get :add_actor, :featured, :archived
        JobOffer.aasm.events.map(&:name).each do |event_name|
          action_name = :"create_and_#{event_name}"
          post :create, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
      end
      member do
        get :export, :board, :stats, :new_transfer, :new_send
        post :transfer, :feature, :unfeature, :send_to_list
        JobOffer.aasm.events.map(&:name).each do |event_name|
          patch(event_name.to_sym)
          action_name = :"update_and_#{event_name}"
          patch :update, constraints: CommitParamConstraint.new(action_name), action: action_name
        end
        namespace :job_offers do
          resources :readings, only: :create
        end
      end
      resources :job_applications, path: "candidatures" do
        member do
          get :cvlm
          get :files
          get :emails
        end
        resource :favorite, only: %i[create destroy]
        resource :unfavorite, only: %i[create destroy]
      end
      resources :archives, only: [:new, :create]
      resources :multiple_recipients_emails, only: %i[new create]
      resources :recipients, only: %i[index create]
    end
    resources :preferred_users, only: :destroy
    resources :preferred_users_lists, path: "liste-candidats" do
      member do
        get :export
        post :send_job_offer
      end
      resources :preferred_users
    end
    resources :users, path: "candidats", except: %i[create] do
      resource :resume, only: %i[show]
      collection do
        post :multi_select
      end
      member do
        get :listing, :photo
        put :update_listing
        post :suspend, :unsuspend, :send_job_offer
      end
    end
    resources :job_applications, path: "candidatures", only: %i[index show update] do
      member do
        patch :change_state
      end
      resources :job_application_files do
        member do
          post :check
          post :uncheck
        end
      end
      resources :rejections, only: %i[create]
      resource :dar, only: %i[update]
      resources :messages, only: %i[create]
      resources :emails, only: %i[create] do
        member do
          post :mark_as_read, :mark_as_unread
          get :attachment
        end
      end
    end
    resources :zip_files, only: :show
    namespace :stats do
      root to: "job_applications#index"
      get :job_offers, to: "job_offers#index"
      resources :job_applications, path: "candidatures", only: %i[index]
    end
    namespace :settings, path: "parametres" do
      resource :positions, only: :update
      resource :organization do
        member do
          get :edit_security
          patch :update_general, :update_display, :update_security
        end
      end
      resources :organization_defaults
      resources :frequently_asked_questions do
        member do
          post :move_higher, :move_lower
        end
      end

      resources :pages do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :cmgs do
        member do
          post :move_higher, :move_lower
        end
      end
      resources :administrators, path: "administrateurs" do
        collection do
          get :export
          get :inactive
        end
        member do
          post :resend_confirmation_instructions
          post :send_unlock_instructions
          post :deactivate
          post :reactivate
          post :transfer
        end
      end
      resources :employers, :categories do
        member do
          post :move_left, :move_right
        end
      end
      resources :salary_ranges
      resources :job_application_file_types
      other_settings = %i[
        availability_ranges
        archiving_reasons benefit drawbacks bops email_template job_application_file_types rejection_reasons
        contract_duration foreign_languages foreign_language_levels job_offer_terms user_menu_links
      ]
      (JobOffer::SETTINGS + other_settings).each do |setting|
        resources setting.to_s.pluralize.to_sym, except: %i[show] do
          member do
            post :move_higher, :move_lower
          end
        end
      end
      root to: "administrators#index"
    end
    root to: "job_offers#index"
  end

  authenticate :user do
    namespace "account", path: "espace-candidat" do
      resource :profiles, path: "mon-profil", only: [] do
        resource :resume, only: :show
        collection do
          get :edit
          patch :update
        end
      end
      resources :job_applications, path: "mes-candidatures" do
        member do
          get :job_offer, path: "offre"
        end
        resources :job_application_files, path: "documents"
        resources :emails, only: %i[index create] do
          member do
            get :attachment
          end
        end
      end
      resource :user, path: "mon-compte", only: %i[show destroy] do
        collection do
          get :edit
          patch :update
        end
        member do
          get :change_email, :change_password, :photo
          patch :update_email, :update_password, :unlink_france_connect, :set_password
        end
      end
    end
  end

  resources :job_offers, path: "offresdemploi", only: %i[index show] do
    collection do
      get :apply
    end
    member do
      get :apply, to: "job_offers#old_apply"
      post :send_application
      get :successful
      resources :bookmarks, only: %i[create destroy], path: "favoris"
    end
  end

  resources :downloads, only: %i[show]
  resources :pages, only: %w[show]
  resource :robots, only: %w[show]
  resource :sitemap
  resource :maintenance, only: %w[show]

  root to: "homepages#show"
end

app/controllers/admin/inherited_resources_controller.rb
# frozen_string_literal: true

class Admin::InheritedResourcesController < Admin::BaseController
  respond_to :html, :json

  helper_method :resource_class, :collection, :resource, :collection_url

  def create
    key = "admin.#{resource_class.to_s.tableize}.create.success"
    resource.administrator = current_administrator if resource.has_attribute?(:administrator_id)
    create!(notice: t(key))
  end

  def update
    key = "admin.#{resource_class.to_s.tableize}.update.success"
    update!(notice: t(key))
  end

  def destroy
    key = "admin.#{resource_class.to_s.tableize}.destroy.success"
    destroy!(notice: t(key))
  end

  protected

  def permitted_fields
    %i[name]
  end

  def permitted_params
    params.require(resource_class.to_s.tableize.singularize.to_sym).permit(permitted_fields)
  end

  alias_method :resource_params, :permitted_params

  def resource_class
    controller_name.classify.constantize
  end

  def resource
    instance_variable_get(:"@#{controller_name.singularize}")
  end

  def collection
    instance_variable_get(:"@#{controller_name}")
  end

  def collection_url
    [:admin, :"#{controller_name}"]
  end
end

app/controllers/admin/settings/inherited_resources_controller.rb
# frozen_string_literal: true

class Admin::Settings::InheritedResourcesController < Admin::Settings::BaseController
  respond_to :html, :json
  inherit_resources
  actions :all, except: %i[show]

  def create
    key = "admin.settings.#{resource_class.to_s.tableize}.create.success"
    resource.organization = current_organization if resource.has_attribute?(:organization_id)
    create!(notice: t(key))
  end

  def update
    key = "admin.settings.#{resource_class.to_s.tableize}.update.success"
    update!(notice: t(key))
  end

  def destroy
    if resource.respond_to?(:children)
      recursive_destroy!(resource)
    else
      resource.destroy!
    end
    redirect_to({action: :index}, flash: {notice: t("admin.settings.#{resource_class.to_s.tableize}.destroy.success")})
  rescue => e
    redirect_to({action: :index}, flash: {notice: t("admin.settings.destroy.failure.#{e.class.name.parameterize.underscore}")})
  end

  def move_higher
    resource.move_higher

    redirect_to action: :index
  end

  def move_lower
    resource.move_lower

    redirect_to action: :index
  end

  def move_left
    resource.move_left

    redirect_to action: :index
  end

  def move_right
    resource.move_right

    redirect_to action: :index
  end

  protected

  def permitted_fields
    %i[name]
  end

  def permitted_params
    params.require(resource_class.to_s.tableize.singularize.to_sym).permit(permitted_fields)
  end

  alias_method :resource_params, :permitted_params

  private

  def recursive_destroy!(resource)
    resource.children.each { |child| recursive_destroy!(child) } if resource.children.any?
    resource.destroy!
  end
end

app/views/admin/inherited_resources/_element.html.haml
%tr
  %td
    - if defined?(level) && level > 0
      %span.text-light-grey{style: "opacity: 0.6;"}= "└#{'──' * (level-1)}"
    = element.try(:name) || element.try(:title)
  - if resource_class == Employer
    %td
      = element.code
  - if resource_class == JobApplicationFileType
    %td
      = JobApplication.human_attribute_name("state/#{element.from_state}")
    %td
      = JobApplication.human_attribute_name("state/#{element.to_state}")
    %td
      = JobApplicationFileType.human_attribute_name("kind/#{element.kind}")
  - if resource_class.reflect_on_association(:job_offers)
    %td.text-center
      = element.job_offers.publicly_visible.count
  %td.text-right
    %ul.list-inline.mb-0.actions
      %li.list-inline-item
        - if resource_class == Category
          = link_to fa_icon('plus'), [:new, :admin, :category, {parent_id: element.id}], title: t('buttons.add_child')
        - if element.has_attribute?(:position)
          = link_to fa_icon('arrow-up'), [:move_higher, :admin, element], method: :post, title: t('buttons.move_higher'), data: {confirm: t('buttons.confirm')}
          = link_to fa_icon('arrow-down'), [:move_lower, :admin, element], method: :post, title: t('buttons.move_lower'), data: {confirm: t('buttons.confirm')}
        = link_to fa_icon('pencil'), [:edit, :admin, element], title: t('buttons.edit')
        = link_to fa_icon('trash-can'), [:admin, element], method: :delete, title: t('buttons.delete'), data: {confirm: t('buttons.confirm')}

app/views/admin/inherited_resources/_form.html.haml
- resource.parent_id = params[:parent_id] if params[:parent_id].present? && resource.new_record?
.card
  .card-body
    = simple_form_for([:admin, resource]) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .form-inputs
        = f.input :name
      .form-actions.text-right.mt-4
        %ul.list-inline.mb-0
          %li.list-inline-item
            = link_to(t('buttons.cancel'), collection_url, class: 'btn btn-body-color mb-0')
          %li.list-inline-item
            = button_tag(type: 'submit', class: 'btn btn-primary btn-raised mb-0') do
              = t("buttons.#{ resource.new_record? ? 'add' : 'edit' }")
              = fa_icon('paper-plane', class: 'ml-1')

app/views/admin/inherited_resources/edit.html.haml
- @page_title = t("admin.#{ resource_class.to_s.tableize }.edit.title", name: resource.try(:name) || resource.try(:title))
= render '/admin/inherited_resources/form'

app/views/admin/inherited_resources/index.html.haml
- @page_title = t("admin.#{ resource_class.to_s.tableize }.#{controller.action_name}.title")
- resource_symbol = resource_class.to_s.tableize.singularize.to_sym
.card
  .card-header.border-bottom-0
    .card-title.d-md-flex.align-items-center
      = t("admin.#{ resource_class.to_s.tableize }.index.card_title", count: collection.size)
      = link_to [:new, :admin, resource_symbol], class: 'btn btn-primary btn-raised ml-auto mt-2 mt-md-0 mb-0' do
        = fa_icon 'plus', class: 'mr-1'
        = t('buttons.add')
  %table.table.table-hover.mb-0.mt-3
    %thead
      %tr
        - if resource_class == EmailTemplate
          %th= resource_class.human_attribute_name(:title)
        - else
          %th= resource_class.human_attribute_name(:name)
          - if resource_class == JobApplicationFileType
            %th= resource_class.human_attribute_name(:from_state)
            %th= resource_class.human_attribute_name(:to_state)
            %th= resource_class.human_attribute_name(:kind)
          - if resource_class == Employer
            %th= resource_class.human_attribute_name(:code)
          - if resource_class.reflect_on_association(:job_offers)
            %th.text-center{style: 'width:100px;'} Nombre d'offres
        %th{style: 'width:120px;'}
    %tbody
      - if resource_class == Category
        - Category.roots.each do |root|
          - Category.each_with_level(root.self_and_descendants) do |category, level|
            = render partial: "/admin/inherited_resources/element", locals: {element: category, level: level}
      - else
        = render partial: "/admin/inherited_resources/element", collection: collection, as: :element

app/views/admin/inherited_resources/new.html.haml
- @page_title = t("admin.#{ resource_class.to_s.tableize }.new.title")
= render 'form'

app/views/admin/inherited_resources/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin_settings_category.name
%p
  %b Position:
  = @admin_settings_category.position

= link_to 'Edit', edit_admin_settings_category_path(@admin_settings_category)
\|
= link_to 'Back', admin_settings_categories_path